import aidenPhoto from "@/assets/images/grantees/aiden-sagerman.jpg";
import danielPhoto from "@/assets/images/grantees/daniel-burger.jpg";
import jennPhoto from "@/assets/images/grantees/jenn-leung.jpg";
import chloePhoto from "@/assets/images/grantees/chloe-loewith.jpg";
import abhinavPhoto from "@/assets/images/grantees/abhinav-singh.jpg";
import noraPhoto from "@/assets/images/grantees/nora-khan.jpg";
import secondsPhoto from "@/assets/images/grantees/seconds-0.jpg";
import yanlinPhoto from "@/assets/images/grantees/yanlin-lu.jpg";
import irisPhoto from "@/assets/images/grantees/iris-long.jpg";

export type GranteeType = "archive" | "experiment" | "tooling";

export interface LinkInfo {
  platform: "x" | "linkedin" | "substack" | "instagram" | "website";
  url: string;
}

export interface Bio {
  name: string;
  text: string;
  photo?: string;
  links?: LinkInfo[];
}

export interface Grantee {
  slug: string;
  names: string;
  type: GranteeType;
  oneLiner: string;
  /** Individual people on the project — one portrait placeholder is rendered per person. */
  people: string[];
  summary: string[];
  bios: Bio[];
  themes: string[];
  /** Copy not yet finalised by the grantee — provisional placeholder text. */
  provisional?: boolean;
}

export const TYPE_LABELS: Record<GranteeType, string> = {
  archive: "Archive",
  experiment: "Experiment",
  tooling: "Tooling",
};

export const TYPE_ORDER: GranteeType[] = ["archive", "experiment", "tooling"];

export const grantees: Grantee[] = [
  {
    slug: "aiden-sagerman",
    names: "Aiden Sagerman",
    type: "archive",
    people: ["Aiden Sagerman"],
    oneLiner:
      "Reconstructing how forms of diagrammatic reasoning changed in topology as the subject became more abstract and algebraic in the twentieth century.",
    summary: [
      `Aiden is reconstructing the changing role of diagrammatic reasoning in algebraic topology over the course of the twentieth century. Much of topology today is done using abstract, algebraic symbolisms, which was not the case a hundred years ago, when topology relied on geometric intuition captured by diagrams. He seeks to reconceptualize this shift not as a disappearance of the diagrammatic, but as a recoding of what it means to reason visually. Using Revival funding to conduct archival visits in the United States, he will zoom in on the development of category theory by Samuel Eilenberg and Saunders Mac Lane from 1942 to 1945, reconstructing the origin of commutative diagrams and their role in the invention of category theory.`,
      `Rooted in the methods of history of science, Aiden's project reconstructs a critical transitioning moment in the history of mathematics, with foundational implications for the missing visual logic in AI development.`,
    ],
    bios: [
      {
        name: "Aiden Sagerman",
        text: `Aiden Sagerman is a PhD student in History of Science at Harvard. His interests span histories of mathematics, quantification, and race and eugenics. He holds a BA in Mathematics and Comparative Literature and Society from Columbia University and an MPhil in History and Philosophy of Science from the University of Cambridge, where he was a Gates Cambridge scholar.`,
        photo: aidenPhoto,
        links: [
          { platform: "website", url: "https://histsci.fas.harvard.edu/people/aiden-sagerman" }
        ]
      },
    ],
    themes: ["Mathematics", "Topology", "Logic", "History", "Geometry"],
  },
  {
    slug: "nora-khan",
    names: "Nora N. Khan",
    type: "archive",
    people: ["Nora N. Khan"],
    oneLiner:
      "Recovering how artistic research collectives built epistemic holding environments, and what their overlooked methods offer for better research cultures.",
    summary: [
      `Nora is recovering the epistemological models generated by forgotten artistic research collectives, identifying replicable elements of organizational design that hold a generative space for the uncertainty and ambiguity of visionary knowledge production. Drawing on collectives like the Detroit Geographic Expedition and Institute and KUNCI Study Forum as case studies, she traces mechanisms of knowledge transmission through archival visits, oral interviews, and essay writing. Each collective reexamines fundamental epistemic virtues: challenging neutral scientific observation, practicing networked cognition, or using speculative narrative as system methodology.`,
      `Nora's project offers an overlooked angle on the metascience discourse. By studying the organizational variables that facilitate breakthrough inquiry, she traces how these collectives functioned as epistemic holding environments, offering renewed perspectives on today's research cultures.`,
    ],
    bios: [
      {
        name: "Nora N. Khan",
        text: `Nora N. Khan is an independent critic, essayist, curator, and educator. Her writing on philosophy of AI and emerging technologies is referenced widely across fields. Formally, this work attempts to theorize the limits of algorithmic knowledge and locate computation’s influence on critical language.
\nShe is a member of the Curatorial Ensemble of the 2026 edition of Counterpublic, one of the nation’s largest public civic exhibitions, titled Coyote Time. She was Co-Curator with Andrea Bellini of the Biennale de L’Image en Mouvement 2024, A Cosmic Movie Camera, hosted by Centre d'Art Contemporain Genève. The edition was the highest-attended in the biennale’s history. As curator of Manual Override at The Shed (2020), she worked with Sondra Perry, Morehshin Allahyari, and Lynn Hershman Leeson on new commissions, in an exhibition that featured major works by Simon Fujiwara and Martine Syms.
\nShe is currently Faculty in Creative Technologies at UCSC, and has served as Arts Council Professor at UCLA in Design Media Arts, History and Theory faculty at SCI-Arc, and professor in Digital + Media at Rhode Island School of Design, where she was nominated for the John R. Frazier Award for Excellence in Teaching. Her books are AI Art and the Stakes for Art Criticism (2026), Seeing, Naming, Knowing (2019) and Fear Indexing the X-Files (2017), with Steven Warwick.`,
        photo: noraPhoto,
      },
    ],
    themes: ["Collectives", "Epistemology", "Metascience", "Organization", "Archives"],
  },
  {
    slug: "iris-long-yanlin-lu",
    names: "Iris Long & Yanlin Lu",
    type: "archive",
    people: ["Iris Long", "Yanlin Lu"],
    oneLiner:
      "Reconstructing the Chinese engagement with anomalous bodily phenomena from 1979-1999.",
    summary: [
      `Iris and Yanlin are reconstructing the forgotten episode of anomalous bodily phenomena research in China from 1979 to 1999, a nationwide program that examined phenomena illegible to modern biomedicine, including extrasensory perception. They will undertake a systematic re-examination of archive materials (scientific publications, conference proceedings, internal reports, and media) and conduct oral interviews with key researchers, practitioners, and observers who participated in or witnessed these experiments.`,
      `This lost program resonates today in its vocabulary of "functional states" of the body as an "open complex giant system," reminiscent of emerging fields like embodied cognition, bioelectric morphogenesis, and systems-based psychosomatic medicine.`,
      `Recovering it reopens questions about how the body senses, integrates, and processes information.`,
    ],
    bios: [
      {
        name: "Yanlin Lu",
        text: `Yanlin LU (ch. 陸衍霖) is a doctoral candidate from the Department of East Asian Studies, Princeton University. He is interested in the structural factors that conditioned knowledge in modern China, and he believes that these underlying factors became more visible when examining unconventional knowledge. To this end, his dissertation traces the history of somatic science, a science of qigong, psychic abilities, and other anomalous bodily capacities that critics called the “greatest pseudoscience movement in contemporary China.” The dissertation shows that the rise and fall of this contested science was underpinned by a broad restructuring of sociopolitical and epistemic order in China’s departure from Maoism.`,
        photo: yanlinPhoto,
        links: [
          { platform: "website", url: "https://eas.princeton.edu/people/yanlin-lu" }
        ]
      },
      {
        name: "Iris Long",
        text: `Iris LONG(ch. 龙星如) is a curator and researcher based between Beijing and London. Her work investigates the intersections of radio technologies, latent space in sciences, and the histories of science and technology in East Asia. Drawing on field research and speculative methodologies, she explores how infrastructures, cosmologies, and forms of knowledge shape cultural imagination and lived experience. Through exhibitions, publications, and long-term interdisciplinary collaborations with artists, scientists and scholars, Long develops experimental platforms for rethinking the relationships between technology, memory, and alternative ways of sensing and understanding the world. Personal website: irislong.xyz`,
        photo: irisPhoto,
        links: [
          { platform: "website", url: "https://irislong.xyz/" },
          { platform: "instagram", url: "https://www.instagram.com/xingru_longiris" }
        ]
      },
    ],
    themes: ["Somatic", "Cognition", "Systems", "Medicine", "Physiology"],
  },
  {
    slug: "daniel-burger",
    names: "Daniel Burger",
    type: "experiment",
    people: ["Daniel Burger"],
    oneLiner:
      "Brain-in-vat with modern perfusion technology, bringing back forgotten research on sustaining living brains outside the body.",
    summary: [
      `Daniel is reviving and modernizing the old research program on isolated brain perfusion: keeping a brain alive and functional outside the body ("brain-in-vat"). His near-term experiment maintains a brain on external life support while gradually transitioning it off the body's own circulation, achieving a living brain sustained independently. The process moves through baseline ECoG recording and a shift to artificial heart-lung support, gradual vascular isolation of the brain, then full separation into a perfusion chamber.`,
      `He's extending a research lineage that ran roughly 1920s–1971 across the USSR and US, from Sergei Brukhonenko's 1925 autojektor to Robert White's 1960s–70s primate brain isolation and monkey head transplant. The program stalled decades ago, but is timely to revive now that organ perfusion has matured into a commercial industry and post-mortem studies show brain tissue's resilience.`,
    ],
    bios: [
      {
        name: "Daniel Burger",
        text: `Daniel Burger is the founder and CEO of Eightsix Science, a neuroengineering company building extracorporeal cognitive preservation of the human brain. He's also a co-founder and chief scientist of Synconetics, a nonprofit pursuing gradual brain replacement as a hardware path to mind uploading (i.e., hybrid mind uploading), founded with Prof. Masataka Watanabe (University of Tokyo). He holds an MSc in Applied Neuroscience from King's College London. Earlier roles at the Blue Brain Project, FinalSpark, and IDUN Technologies gave him a substrate-level feel for how living neural tissue behaves.`,
        photo: danielPhoto,
        links: [
          { platform: "x", url: "https://x.com/danburonline" },
          { platform: "linkedin", url: "https://www.linkedin.com/in/danburonline/" },
          { platform: "substack", url: "https://danburonline.substack.com" },
          { platform: "instagram", url: "https://instagram.com/danburonline" }
        ]
      },
    ],
    themes: ["Neurobiology", "Perfusion", "Uploading", "Physiology", "Preservation"],
  },
  {
    slug: "jenn-leung-chloe-loewith",
    names: "Jenn Leung & Chloe Loewith",
    type: "experiment",
    people: ["Jenn Leung", "Chloe Loewith"],
    oneLiner:
      "Inspired by Alife, using multiplayer games to benchmark Synthetic Bioengineered Intelligence (SBI).",
    summary: [
      `Jenn and Chloe are reviving the older research tradition of "Artificial Life" with a new engineering toolkit for benchmarking Synthetic Biological Intelligence (SBI): an emerging field that fuses living biological matter with electronic hardware to create self-learning, biohybrid systems. Using multiplayer games as an interface for communicating with these biological materials, they focus on constructing an environment for SBI rather than directly programming behaviors, allowing researchers to train neuronal cultures as game agents and to establish reproducible benchmarking standards.`,
      `"Inspired by the "bottom-up" approach to Artificial Life, with its emphasis on emergence and complex systems, Jenn and Chloe take on a foundational gap in the field: the lack of a unified standard for encoding information to neurons, a problem they approach as a design challenge.`,
    ],
    bios: [
      {
        name: "Jenn Leung",
        text: `Jenn Leung is a researcher and creative technologist working at the intersection of synthetic biology, real-time simulation, and living neural systems. She is a Senior Lecturer in Creative Technology & Design at University of the Arts London, a researcher at LifeFabs Institute, and a Visiting Researcher at The Bartlett School of Architecture, UCL, working on the 100 Minds in Motion project combining EEG, eye-tracking, and movement data within agent-based simulation. Her research currently focuses on developing Unreal Engine interfaces for living neurons and agent behaviour simulations. Two papers have recently been published in the MIT Antikythera Journal, and a paper on UE-API for brain-on-a-chip platforms was presented at NeurIPS 2025. Since 2025, she has collaborated with the biocomputing start-up Cortical Labs to create human-synthetic biological intelligence visualizations. In 2026, she is also collaborating with Michael Levin, Agnieszka Kurant, and Emily Ertle for Rhizome’s 7x7 programme.`,
        photo: jennPhoto,
        links: [
          { platform: "website", url: "https://jennleung.xyz/" },
          { platform: "website", url: "https://researchers.arts.ac.uk/2393-jenn-leung" },
          { platform: "instagram", url: "https://www.instagram.com/jennnital/" }
        ]
      },
      {
        name: "Chloe Loewith",
        text: `Chloe Loewith is a researcher and writer working across synthetic biology, biomedical AI, and philosophy. She is a philosophy of technology researcher at NYU, and was previously a researcher at Antikythera’s Cognitive Infrastructures Studio, a functional genomic bioethics researcher at SFU, and graduate student at the University of Cambridge Center for the Future of Intelligence. Her work has appeared in the MIT Antikythera Journal, TANK Magazine, AI & Society, Bianjie, HERVISIONS, PhysioNet and the Whole Earth Redux. Her current research explores hybrid ecologies and co-evolutionary human-AI interaction, with a focus on cognitive assemblages, fluid ontologies, and distributed cognition.`,
        photo: chloePhoto,
        links: [
          { platform: "linkedin", url: "http://www.linkedin.com/in/chloe-loewith" }
        ]
      },
    ],
    themes: ["Alife", "Biohybrid", "Biology", "Neurons", "Games"],
  },
  {
    slug: "abhinav-singh",
    names: "Abhinav Singh",
    type: "experiment",
    people: ["Abhinav Singh"],
    oneLiner:
      "Reviving molecular inference by building DNA Learning Systems for programmable biology: sequences that learn, adapt, and act through chemistry.",
    summary: [
      `Abhinav is developing DNA Learning Systems. Chemical systems where DNA or RNA molecules do more than store information. They interact, update, and respond in ways that can support tasks like classification, inference, forecasting, and AI training. The project combines large-scale sequence engineering with experimental molecular computing. The team will take an existing DNA-based learning design and turn it into a reliable engineering pipeline: simulate how the molecular system behaves, predict where it fails, use large-scale computation to redesign the DNA sequences, and then compare those predictions against real lab measurements.`,
      `The goal is to make DNA based learning a repeatable engineering paradigm. Earlier work showed that DNA molecules can, in principle, perform gradient-descent like computation through reaction networks. Though the field generated considerable excitement in the 2000s-2010, it stalled because real molecules leak and cross-react limits the number of controlled reactions. Today, advances in AI, optimization, and biological sequence design make it possible to revisit the field with better tools making the revival timely.`,
    ],
    bios: [
      {
        name: "Abhinav Singh",
        text: `Abhinav Singh is a computational scientist and engineer working at the intersection of out-of-equilibrium physics, supercomputer simulations, and learning systems. His previous work includes large-scale 3D physics simulations of tissue and cellular mechanics as active fluids, high-performance computing, and chemical-reaction-network models for learning and inference. He has worked on simulating complex biological and physical systems, building scientific software infrastructure, and developing algorithms that connect computation with chemistry. In this project, he leads the simulation, optimization, and DNA sequence-engineering pipeline.`,
        photo: abhinavPhoto,
        links: [
          { platform: "x", url: "https://x.com/abhinavsns" },
          { platform: "linkedin", url: "https://www.linkedin.com/in/abhinavsns/" },
          { platform: "instagram", url: "https://instagram.com/abhinavsns" }
        ]
      },
    ],
    themes: ["Computing", "DNA", "Chemistry", "Nanotechnology", "Genetics"],
  },
  {
    slug: "seconds-0",
    names: "Seconds_0",
    type: "tooling",
    people: ["Seconds_0"],
    oneLiner:
      "Building an automated pipeline for translating Soviet research papers into English.",
    summary: [
      `Seconds_0 is building tooling for recovering Soviet research archives, beginning with an automated pipeline for translating Soviet research papers into English. Adapted from the infrastructure he developed for Chinarxiv.org, the pipeline uses frontier models vision capabilities to read, understand, and accurately translate academic papers, including mathematical formulas, tables, and diagrams. He is also developing a website to house the database of translated papers, featuring tools to search the corpus in natural language.`,
      `The project responds to a significant need to revisit Soviet research archives. As English became the dominant language of 20th-century science, Russian journal papers had a diminishing international impact due to translation costs and the dominance of English-language indexing systems. Seconds_0's pipeline enables Revival to reproduce these translations with greater precision, surfacing high-value "alpha" papers that offer tangible relevance to contemporary research.`,
    ],
    bios: [
      {
        name: "Seconds_0",
        text: `Seconds is an obsessive dabbler in all things technology and health. He created ChinaRxiv.org, an automated translation project that brings Chinese research preprints into English, and has a mountain of other AI experiments - some useful, many strange, and most mercifully forgotten. Outside of his day job as a product manager, he LARPs as a homesteader with his wife, two children, and an ancient dog. He can be found at @seconds_0 on X.`,
        photo: secondsPhoto,
        links: [
          { platform: "website", url: "https://seconds0.com" },
          { platform: "x", url: "https://x.com/seconds_0" }
        ]
      },
    ],
    themes: ["Archives", "Translation", "Soviet", "AI", "Corpus"],
  },
];

export function getGrantee(slug: string): Grantee | undefined {
  return grantees.find((g) => g.slug === slug);
}
